// frontend-react/src/components/FilePreview/FilePreview.tsx
import React, { useState, useEffect, useRef } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Box,
  Typography,
  IconButton,
  CircularProgress,
  Alert,
  useTheme,
  Zoom,
  Fab,
  Tooltip
} from '@mui/material';
import {
  Close as CloseIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
  RotateLeft as RotateLeftIcon,
  RotateRight as RotateRightIcon,
  Fullscreen as FullscreenIcon,
  Download as DownloadIcon,
  PlayArrow as PlayIcon,
  Pause as PauseIcon,
  VolumeUp as VolumeIcon
} from '@mui/icons-material';

export interface FilePreviewProps {
  file: File | null;
  open: boolean;
  onClose: () => void;
  onDownload?: () => void;
}

interface PreviewState {
  loading: boolean;
  error: string | null;
  zoom: number;
  rotation: number;
  currentPage: number;
  totalPages: number;
}

const FilePreview: React.FC<FilePreviewProps> = ({
  file,
  open,
  onClose,
  onDownload
}) => {
  const theme = useTheme();
  const [previewState, setPreviewState] = useState<PreviewState>({
    loading: false,
    error: null,
    zoom: 1,
    rotation: 0,
    currentPage: 1,
    totalPages: 1
  });
  
  const [fileUrl, setFileUrl] = useState<string | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);
  const audioRef = useRef<HTMLAudioElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  // File type detection
  const getFileType = (file: File): string => {
    const extension = (file.name || '').toLowerCase().split('.').pop() || '';
    
    if (['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'].includes(extension)) {
      return 'image';
    }
    if (['mp4', 'webm', 'ogg', 'mov', 'avi'].includes(extension)) {
      return 'video';
    }
    if (['mp3', 'wav', 'ogg', 'aac', 'm4a'].includes(extension)) {
      return 'audio';
    }
    if (extension === 'pdf') {
      return 'pdf';
    }
    if (['doc', 'docx', 'txt', 'rtf'].includes(extension)) {
      return 'document';
    }
    return 'unknown';
  };

  // Create file URL when file changes
  useEffect(() => {
    if (file && open) {
      setPreviewState(prev => ({ ...prev, loading: true, error: null }));
      
      try {
        const url = URL.createObjectURL(file);
        setFileUrl(url);
        setPreviewState(prev => ({ ...prev, loading: false }));
      } catch (error) {
        setPreviewState(prev => ({ 
          ...prev, 
          loading: false, 
          error: 'Error al cargar el archivo' 
        }));
      }
    }

    return () => {
      if (fileUrl) {
        URL.revokeObjectURL(fileUrl);
        setFileUrl(null);
      }
    };
  }, [file, open]);

  // Reset state when dialog closes
  useEffect(() => {
    if (!open) {
      setPreviewState({
        loading: false,
        error: null,
        zoom: 1,
        rotation: 0,
        currentPage: 1,
        totalPages: 1
      });
      setIsPlaying(false);
    }
  }, [open]);

  const handleZoomIn = () => {
    setPreviewState(prev => ({ ...prev, zoom: Math.min(prev.zoom * 1.2, 5) }));
  };

  const handleZoomOut = () => {
    setPreviewState(prev => ({ ...prev, zoom: Math.max(prev.zoom / 1.2, 0.1) }));
  };

  const handleRotateLeft = () => {
    setPreviewState(prev => ({ ...prev, rotation: prev.rotation - 90 }));
  };

  const handleRotateRight = () => {
    setPreviewState(prev => ({ ...prev, rotation: prev.rotation + 90 }));
  };

  const handlePlayPause = () => {
    if (videoRef.current) {
      if (isPlaying) {
        videoRef.current.pause();
      } else {
        videoRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
    
    if (audioRef.current) {
      if (isPlaying) {
        audioRef.current.pause();
      } else {
        audioRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  const renderImagePreview = () => (
    <Box
      sx={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: '400px',
        maxHeight: '70vh',
        overflow: 'auto',
        bgcolor: 'grey.100',
        borderRadius: 2,
        position: 'relative'
      }}
    >
      <img
        src={fileUrl || ''}
        alt={file?.name}
        style={{
          maxWidth: '100%',
          maxHeight: '100%',
          transform: `scale(${previewState.zoom}) rotate(${previewState.rotation}deg)`,
          transition: 'transform 0.3s ease',
          objectFit: 'contain'
        }}
        onError={() => setPreviewState(prev => ({ 
          ...prev, 
          error: 'Error al cargar la imagen' 
        }))}
      />
      
      {/* Image controls */}
      <Box
        sx={{
          position: 'absolute',
          bottom: 16,
          right: 16,
          display: 'flex',
          gap: 1,
          bgcolor: 'rgba(0, 0, 0, 0.7)',
          borderRadius: 2,
          p: 1
        }}
      >
        <IconButton 
          size="small" 
          onClick={handleZoomIn} 
          sx={{ color: 'white' }}
          title="Acercar"
        >
          <ZoomInIcon />
        </IconButton>
        <IconButton 
          size="small" 
          onClick={handleZoomOut} 
          sx={{ color: 'white' }}
          title="Alejar"
        >
          <ZoomOutIcon />
        </IconButton>
        <IconButton 
          size="small" 
          onClick={handleRotateLeft} 
          sx={{ color: 'white' }}
          title="Rotar izquierda"
        >
          <RotateLeftIcon />
        </IconButton>
        <IconButton 
          size="small" 
          onClick={handleRotateRight} 
          sx={{ color: 'white' }}
          title="Rotar derecha"
        >
          <RotateRightIcon />
        </IconButton>
      </Box>
    </Box>
  );

  const renderVideoPreview = () => (
    <Box
      sx={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: '400px',
        maxHeight: '70vh',
        bgcolor: 'grey.900',
        borderRadius: 2,
        position: 'relative'
      }}
    >
      <video
        ref={videoRef}
        src={fileUrl || ''}
        controls
        style={{
          maxWidth: '100%',
          maxHeight: '100%',
          borderRadius: theme.shape.borderRadius
        }}
        onPlay={() => setIsPlaying(true)}
        onPause={() => setIsPlaying(false)}
        onError={() => setPreviewState(prev => ({ 
          ...prev, 
          error: 'Error al cargar el video' 
        }))}
      >
        Tu navegador no soporta la reproducción de video.
      </video>
    </Box>
  );

  const renderAudioPreview = () => (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '300px',
        bgcolor: 'grey.50',
        borderRadius: 2,
        p: 4
      }}
    >
      <VolumeIcon sx={{ fontSize: 80, color: 'primary.main', mb: 3 }} />
      
      <Typography variant="h6" component="div" sx={{ mb: 2, textAlign: 'center' }}>
        {file?.name}
      </Typography>
      
      <audio
        ref={audioRef}
        src={fileUrl || ''}
        controls
        style={{ width: '100%', maxWidth: '400px' }}
        onPlay={() => setIsPlaying(true)}
        onPause={() => setIsPlaying(false)}
        onError={() => setPreviewState(prev => ({ 
          ...prev, 
          error: 'Error al cargar el audio' 
        }))}
      >
        Tu navegador no soporta la reproducción de audio.
      </audio>
    </Box>
  );

  const renderPdfPreview = () => (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '400px',
        bgcolor: 'grey.50',
        borderRadius: 2,
        p: 4
      }}
    >
      <Typography variant="h6" component="div" sx={{ mb: 2 }}>
        Vista previa de PDF
      </Typography>
      
      <iframe
        src={`${fileUrl}#toolbar=1&navpanes=1&scrollbar=1`}
        width="100%"
        height="500px"
        style={{
          border: 'none',
          borderRadius: theme.shape.borderRadius
        }}
        title={file?.name}
      />
    </Box>
  );

  const renderDocumentPreview = () => (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '300px',
        bgcolor: 'grey.50',
        borderRadius: 2,
        p: 4
      }}
    >
      <Typography variant="h6" component="div" sx={{ mb: 2 }}>
        Documento: {file?.name}
      </Typography>
      
      <Typography variant="body2" component="div" color="text.secondary" sx={{ mb: 3, textAlign: 'center' }}>
        La vista previa de documentos no está disponible. 
        Puedes descargar el archivo para verlo.
      </Typography>
      
      {onDownload && (
        <Button
          variant="contained"
          startIcon={<DownloadIcon />}
          onClick={onDownload}
        >
          Descargar documento
        </Button>
      )}
    </Box>
  );

  const renderUnsupportedPreview = () => (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '300px',
        bgcolor: 'grey.50',
        borderRadius: 2,
        p: 4
      }}
    >
      <Typography variant="h6" component="div" sx={{ mb: 2 }}>
        Vista previa no disponible
      </Typography>
      
      <Typography variant="body2" component="div" color="text.secondary" sx={{ mb: 3, textAlign: 'center' }}>
        El tipo de archivo {file?.name.split('.').pop()?.toUpperCase()} no es compatible con la vista previa.
      </Typography>
      
      {onDownload && (
        <Button
          variant="contained"
          startIcon={<DownloadIcon />}
          onClick={onDownload}
        >
          Descargar archivo
        </Button>
      )}
    </Box>
  );

  const renderPreviewContent = () => {
    if (previewState.loading) {
      return (
        <Box
          sx={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            minHeight: '300px'
          }}
        >
          <CircularProgress />
        </Box>
      );
    }

    if (previewState.error) {
      return (
        <Alert severity="error" sx={{ m: 2 }}>
          {previewState.error}
        </Alert>
      );
    }

    if (!file || !fileUrl) {
      return null;
    }

    const fileType = getFileType(file);

    switch (fileType) {
      case 'image':
        return renderImagePreview();
      case 'video':
        return renderVideoPreview();
      case 'audio':
        return renderAudioPreview();
      case 'pdf':
        return renderPdfPreview();
      case 'document':
        return renderDocumentPreview();
      default:
        return renderUnsupportedPreview();
    }
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="lg"
      fullWidth
      PaperProps={{
        sx: {
          minHeight: '60vh',
          maxHeight: '90vh'
        }
      }}
    >
      <DialogTitle
        sx={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          pb: 1
        }}
      >
        <Box component="div" sx={{ flex: 1 }}>
          <Typography variant="h6" component="span">
            {file?.name}
          </Typography>
        </Box>
        
        <Box sx={{ display: 'flex', gap: 1 }}>
          {onDownload && (
            <IconButton onClick={onDownload} size="small" title="Descargar">
              <DownloadIcon />
            </IconButton>
          )}
          
          <IconButton onClick={onClose} size="small" title="Cerrar">
            <CloseIcon />
          </IconButton>
        </Box>
      </DialogTitle>

      <DialogContent sx={{ p: 0, overflow: 'hidden' }}>
        {renderPreviewContent()}
      </DialogContent>

      <DialogActions sx={{ p: 2 }}>
        <Box sx={{ flex: 1 }}>
          <Typography variant="body2" color="text.secondary" component="span">
            {file && file.size !== undefined && file.size > 0 
              ? `Tamaño: ${(file.size / 1024 / 1024).toFixed(2)} MB`
              : file && file.size === 0
              ? 'Tamaño: 0 MB'
              : 'Tamaño: No disponible'
            }
          </Typography>
        </Box>
        
        <Button onClick={onClose} variant="outlined">
          Cerrar
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default FilePreview;

// frontend/voc/src/app/components/file-preview/file-preview.component.ts
import { LucideIconComponent } from '../lucide-icon/lucide-icon.component';
import { CachedImagePipe } from '../../pipes/cached-image.pipe';
import { Component, input, output, signal, effect, computed, OnDestroy, model } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ButtonModule } from 'primeng/button';
import { DialogModule } from 'primeng/dialog';
import { TooltipModule } from 'primeng/tooltip';
import { ProgressBarModule } from 'primeng/progressbar';
import { SafeUrlPipe } from '../../pipes/safe-url.pipe';

@Component({
  selector: 'app-file-preview',
  standalone: true,
  imports: [
    LucideIconComponent,
    CachedImagePipe,CommonModule, ButtonModule, DialogModule, TooltipModule, ProgressBarModule, SafeUrlPipe],
  templateUrl: './file-preview.component.html',
  styleUrls: ['./file-preview.component.scss']
})
export class FilePreviewComponent implements OnDestroy {
  file = input<File | string | null>(null);
  fileName = input<string>('');
  fileSize = input<number>(0);
  visible = model<boolean>(false);
  onDownload = output<void>();

  fileUrl = signal<string | null>(null);
  zoom = signal<number>(1);
  rotation = signal<number>(0);
  error = signal<string | null>(null);
  loading = signal<boolean>(false);
  downloading = signal<boolean>(false);
  downloadProgress = signal<number>(0);

  displayName = computed(() => {
    const fileData = this.file();
    if (fileData instanceof File) return fileData.name;
    return this.fileName() || 'Archivo';
  });

  fileType = computed(() => {
    const fileData = this.file();
    if (!fileData) return 'unknown';

    let name = '';
    if (fileData instanceof File) {
      name = fileData.name;
    } else {
      name = this.fileName() || (typeof fileData === 'string' ? fileData : '');
    }

    const extension = (name || '').toLowerCase().split('.').pop() || '';
    if (['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'].includes(extension)) return 'image';
    if (['mp4', 'webm', 'ogg', 'mov', 'avi'].includes(extension)) return 'video';
    if (['mp3', 'wav', 'ogg', 'aac', 'm4a'].includes(extension)) return 'audio';
    if (extension === 'pdf') return 'pdf';
    if (['pptx', 'ppt'].includes(extension)) return 'presentation';
    if (['doc', 'docx', 'txt', 'rtf'].includes(extension)) return 'document';
    return 'unknown';
  });

  presentationUrl = computed(() => {
    const url = this.fileUrl();
    const type = this.fileType();
    if (type === 'presentation' && url) {

      return `https://view.officeapps.live.com/op/embed.aspx?src=${encodeURIComponent(url)}`;
    }
    return null;
  });

  constructor() {
    effect(() => {

      const fileData = this.file();
      const isVisible = this.visible();
      const type = this.fileType();
      const size = this.fileSize();

      if (fileData && isVisible) {

        if (type === 'presentation' && size > 250 * 1024 * 1024) {
          this.error.set('El archivo es demasiado grande para previsualizarlo con el visor de Office (Máximo 250MB). Por favor, descárgalo para verlo.');
          return;
        }

        try {
          this.loading.set(true);
          if (fileData instanceof File) {
            const url = URL.createObjectURL(fileData);
            this.fileUrl.set(url);
          } else if (typeof fileData === 'string') {
            this.fileUrl.set(fileData);
          }
          this.resetState();
          this.error.set(null);
        } catch (e) {
          this.error.set('Error al cargar el archivo');
          this.loading.set(false);
        }
      } else {
        this.cleanupUrl();
      }
    });
  }

  onLoadComplete() {
    this.loading.set(false);
  }

  ngOnDestroy() {
    this.cleanupUrl();
  }

  private cleanupUrl() {

    const url = this.fileUrl();
    if (url && url.startsWith('blob:')) {
      URL.revokeObjectURL(url);
    }
    this.fileUrl.set(null);
  }

  onHide() {
    this.visible.set(false);
    this.resetState();
  }

  resetState() {
    this.zoom.set(1);
    this.rotation.set(0);
  }

  zoomIn() {
    this.zoom.update(z => Math.min(z * 1.2, 5));
  }

  zoomOut() {
    this.zoom.update(z => Math.max(z / 1.2, 0.1));
  }

  rotateLeft() {
    this.rotation.update(r => r - 90);
  }

  rotateRight() {
    this.rotation.update(r => r + 90);
  }

  download() {
    this.downloading.set(true);
    this.downloadProgress.set(0);
    this.onDownload.emit();
  }

  setDownloadProgress(progress: number) {
    this.downloadProgress.set(progress);
    if (progress >= 100) {
      setTimeout(() => {
        this.downloading.set(false);
        this.downloadProgress.set(0);
      }, 1000);
    }
  }

  resetDownloadState() {
    this.downloading.set(false);
    this.downloadProgress.set(0);
  }

  handleError(type: string) {
    this.error.set(`Error al cargar ${type}`);
  }
}

<p-dialog [(visible)]="visible" [modal]="true" [style]="{width: '80vw', maxWidth: '1000px'}" [maximizable]="true"
    [draggable]="false" [resizable]="false" (onHide)="onHide()" [header]="displayName()" styleClass="p-0">

    <div class="flex flex-column align-items-center justify-content-center min-h-30rem bg-black-alpha-90 border-round relative overflow-hidden p-4"
        *ngIf="!error()">

        <!-- Loading Overlay -->
        <div *ngIf="loading()" class="absolute top-0 left-0 w-full h-full flex flex-column align-items-center justify-content-center bg-black-alpha-70 z-5">
            <lucide-icon name="loader-2" class="lucide-spin text-white" style="width: 3rem; height: 3rem;"></lucide-icon>
            <span class="text-white mt-3 font-medium">Cargando archivo pesado...</span>
            <span class="text-white-alpha-70 text-sm mt-1">Esto puede tardar dependiendo de tu conexión</span>
        </div>

        <!-- Image Preview -->
        <ng-container *ngIf="fileType() === 'image' && fileUrl()">
            <div class="overflow-auto w-full h-full flex align-items-center justify-content-center"
                style="max-height: 70vh;">
                <img [src]="fileUrl() | safeUrl | cachedImage" [alt]="displayName()"
                    class="transition-transform transition-duration-300"
                    [style.transform]="'scale(' + zoom() + ') rotate(' + rotation() + 'deg)'"
                    style="max-width: 100%; max-height: 100%; object-fit: contain;" 
                    (load)="onLoadComplete()"
                    (error)="handleError('la imagen')">
            </div>

            <!-- Controls -->
            <div class="absolute bottom-0 right-0 m-3 flex gap-2 bg-black-alpha-70 border-round p-2 z-5" *ngIf="!loading()">
                <p-button [rounded]="true" [text]="true" styleClass="text-white hover:bg-white-alpha-10" (onClick)="zoomIn()" pTooltip="Acercar"><lucide-icon name="search-plus"></lucide-icon></p-button>
                <p-button [rounded]="true" [text]="true" styleClass="text-white hover:bg-white-alpha-10" (onClick)="zoomOut()" pTooltip="Alejar"><lucide-icon name="search-minus"></lucide-icon></p-button>
                <p-button [rounded]="true" [text]="true" styleClass="text-white hover:bg-white-alpha-10" (onClick)="rotateLeft()" pTooltip="Rotar Izquierda"><lucide-icon name="refresh-cw"></lucide-icon></p-button>
                <p-button [rounded]="true" [text]="true" styleClass="text-white hover:bg-white-alpha-10" [style]="{ transform: 'scaleX(-1)' }" (onClick)="rotateRight()" pTooltip="Rotar Derecha"><lucide-icon name="refresh-cw"></lucide-icon></p-button>
            </div>
        </ng-container>

        <!-- Video Preview -->
        <ng-container *ngIf="fileType() === 'video' && fileUrl()">
            <video [src]="fileUrl() | safeUrl" controls class="w-full max-h-30rem border-round"
                (loadeddata)="onLoadComplete()"
                (error)="handleError('el video')">
                Tu navegador no soporta la reproducción de video.
            </video>
        </ng-container>

        <!-- Audio Preview -->
        <ng-container *ngIf="fileType() === 'audio' && fileUrl()">
            <div class="flex flex-column align-items-center gap-4 p-5 bg-white border-round w-full max-w-30rem">
                <lucide-icon name="volume-2" class="text-6xl text-primary"></lucide-icon>
                <div class="text-xl font-medium text-900 text-center">{{ displayName() }}</div>
                <audio [src]="fileUrl() | safeUrl" controls class="w-full" 
                    (loadeddata)="onLoadComplete()"
                    (error)="handleError('el audio')">
                    Tu navegador no soporta la reproducción de audio.
                </audio>
            </div>
        </ng-container>

        <!-- PDF Preview -->
        <ng-container *ngIf="fileType() === 'pdf' && fileUrl()">
            <iframe [src]="(fileUrl() + '#toolbar=1&navpanes=1&scrollbar=1') | safeUrl" width="100%" height="600px"
                class="border-none border-round bg-white"
                (load)="onLoadComplete()"></iframe>
        </ng-container>

        <!-- Presentation Preview (PPTX) -->
        <ng-container *ngIf="fileType() === 'presentation' && presentationUrl()">
            <iframe [src]="presentationUrl()! | safeUrl" width="100%" height="600px"
                class="border-none border-round bg-white"
                (load)="onLoadComplete()">
            </iframe>
        </ng-container>

        <!-- Document/Other Preview -->
        <ng-container *ngIf="fileType() === 'document' || fileType() === 'unknown'">
            <div class="flex flex-column align-items-center gap-3 p-5 bg-white border-round">
                <lucide-icon name="file" class="text-6xl text-gray-500"></lucide-icon>
                <div class="text-xl font-medium text-900">Vista previa no disponible</div>
                <div class="text-gray-600 text-center">
                    El archivo {{ displayName() }} no se puede previsualizar.<br>
                    Descárgalo para verlo.
                </div>
                <p-button (onClick)="download()"><lucide-icon name="download" class="mr-2"></lucide-icon>Descargar</p-button>
            </div>
        </ng-container>
    </div>

    <!-- Error State -->
    <div class="flex flex-column align-items-center justify-content-center min-h-20rem gap-3 p-5" *ngIf="error()">
        <lucide-icon name="alert-circle" class="text-6xl text-red-500"></lucide-icon>
        <div class="text-xl font-medium text-red-500 text-center max-w-30rem">{{ error() }}</div>
        <div class="flex flex-column align-items-center gap-3 mt-2">
            <p-button [label]="downloading() ? 'Descargando... ' + downloadProgress() + '%' : 'Descargar'" 
                (onClick)="download()" 
                severity="danger"
                [disabled]="downloading()">
                <lucide-icon [name]="downloading() ? 'loader-2' : 'download'" [class.lucide-spin]="downloading()" class="mr-2"></lucide-icon>
            </p-button>
            
            <div *ngIf="downloading()" class="w-full max-w-20rem">
                <p-progressBar [value]="downloadProgress()" [showValue]="false" [style]="{'height': '6px'}"></p-progressBar>
            </div>
        </div>
    </div>
</p-dialog>
